import actions from './actions.js'
import mutations from './mutations.js'
import getters from './getters.js'

export default {
  namespaced: true,
  state() {
    return {
      isLoading: false,
      hostEvents: [],
      eventa: [
        {
          id: 1001,
          title: 'Neon Nights Music Festival',
          category: 'Carnival',
          date: 'Apr 15, 2026',
          time: '8:00 PM',
          location: 'Central Park, New York',
          price: 89,
          attendees: '2.4k',
          ticketsLeft: 45,
          totalTickets: 500,
          saleStatus: 'Selling Fast',
          eventStatus: 'Sold Out',
          featured: true,
          isFavorite: false,
          image:
            'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=400&fit=crop',
        },
        {
          id: 1002,
          title: 'Tech Innovation Summit 2026',
          category: 'Conference',
          date: 'May 20, 2026',
          time: '9:00 AM',
          location: 'Convention Center, SF',
          price: 299,
          attendees: '850',
          ticketsLeft: 120,
          totalTickets: 1000,
          saleStatus: 'On Sale',
          eventStatus: 'active',
          featured: true,
          isFavorite: true,
          image:
            'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=400&fit=crop',
        },
        {
          id: 10033,
          title: 'Championship Basketball Finals',
          category: 'Entertainment',
          date: 'Jun 12, 2026',
          time: '7:30 PM',
          location: 'Madison Square Garden',
          price: 150,
          attendees: '15k',
          ticketsLeft: 8,
          totalTickets: 200,
          saleStatus: 'Selling Fast',
          eventStatus: 'active',
          featured: false,
          isFavorite: false,
          image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        },
        {
          id: 1004,
          title: 'Modern Art Exhibition Opening',
          category: 'Party',
          date: 'Apr 22, 2026',
          time: '6:00 PM',
          location: 'MoMA, New York',
          price: 45,
          attendees: '320',
          ticketsLeft: 0,
          totalTickets: 400,
          saleStatus: 'Sold Out',
          eventStatus: 'active',
          featured: false,
          isFavorite: false,
          image:
            'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800&h=400&fit=crop',
        },
        {
          id: 1005,
          title: 'Street Food Festival Weekend',
          category: 'Dinner',
          date: 'Jul 8, 2026',
          time: '12:00 PM',
          location: 'Waterfront Park',
          price: 25,
          attendees: '5k',
          ticketsLeft: 500,
          totalTickets: 2000,
          saleStatus: 'On Sale',
          eventStatus: 'active',
          featured: false,
          isFavorite: false,
          image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=400&fit=crop',
        },
        {
          id: 1006,
          title: 'Indie Rock Concert Series',
          category: 'Concert',
          date: 'May 5, 2026',
          time: '7:00 PM',
          location: 'The Fillmore, SF',
          price: 65,
          attendees: '1.2k',
          ticketsLeft: 23,
          totalTickets: 300,
          saleStatus: 'Sold Out',
          eventStatus: 'active',
          featured: true,
          isFavorite: true,
          image:
            'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&h=400&fit=crop',
        },
      ],

      events: [],

      featuredEvents: [],

      // options
      statusOptions: ['On Sale', 'Selling Fast', 'Sold Out'],
      categories: ['Concert', 'Conference', 'Carnival', 'Entertainment', 'Party', 'Dinner'],
    }
  },
  actions,
  mutations,
  getters,
}
